# Meta verso y porquería

en una charla de académicos sobre memes

a un costado de la ciudad

la alameda del fondo se bate en discursos

no autorizados por el evento un viejo


quizá guerrillero veterano traza el contraste

entre la dominación militar de los 70s

y la dominación tecnológica de este siglo


uno que vino en carreta trayendo 

en sus crines un fueguito 

a la vereda amiga


interviene y grita que 

le deprime te juro me dan ganas de llorar

tanta gente hablando y tanto tiempo de pantallitas

salgan de la televisión manga de


yo estuve internado en dos neuro-

psiquiátricos en esta ciudad el primero

acá cerquita al lado de la cárcel

el segundo era una tumba entre los bordes de la realidad digital 

afuera de las redes sociales del estatus y de los likes


pero toda la escena se desviste ahora

en condescendencias inquietas que aplacan las contradicciones del pastito 

analógico sobre el que se sostiene la conversa


inexistente de las redes subjetivantes

y los productos culturales que tensionan cada vez más


nuestra senilidad cyborg con nuestros cuerpos

latinoamericanos bola de cringe


frío en la avenida ahora una chica


toca instrumentos caros para cantar

odas al bloqueo gente en internet y me abandono

contentísima a los cauces 

de la depresión autolesiva


igual la loca no soy yo porque estetizo dicen

toda una sensibilidad naturalizada por la

neo burguevanguardia glitcheada en tocs


audiencia y sabios entonces escuchan

y simulan bailar en este castillo


que encima dieron por llamar caos o

salud mental o

una revista cultural medio tongocha


para las conciencias privilecarizadas del pero

más tarde cuando otro muchacho ajusta


una guitarra acústica -la vieja viola


el jardín de la casona sufre ahora y de nuevo

el abandono se acrecientan entonces

los yuyos y los flujos 


centrífugos de tráfico humano

ya es de noche quizá el músico él sí


un loquito pueda convertirse en lobizón


o de mínima generar de pronto aullidos

anacrónicos que incomoden por de más ciertas

cámaras de eco-

lalia o la estabilidad 


simbólica de un mundo enrarecido

que ahora se pierde en esquinas medio zumbantes

de fantasmitas intemporales


y entra sin mucha seguridad pero sí

con un latentísimo agobio medio galopando


a todos los planos de ese infierno que dimos

por llamar circulación de mercancías y reproducción incesante de capital
