# no sé si es el qué o este cielo

    _Estamos en una encrucijada de caminos que parten y caminos que vuelven._
    Raúl González Tuñón


para que bebamos la dulce fritura

del vendedor de punta lara


para que amemos santiago y managua

la paz y chiapas, pampas y cerros


los grises barquitos areneros 

y la luz de las altas rompientes de la tarde


encendidas para los detectores de metales

y para los ladrones


y las placas en donde los yanarkas

tragan polillas nocturnas, escarabajos


y les niñes pochoclos del pochoclero

y bajo el sol y bajo los eucaliptos


entre ágiles malambos suenan

todas las cuerdas


placas, dije, las placas

continentales, platillos

del bajo caracas para el tambor


que es esa voz bajando

por el juncal alegre


tener un corazón ligero! vale decir

amar a todas las personas bellas


y una ética fiera, vale decir, andar

con fisuras alegres y dormir 


en una sombra un ocaso cualquiera

y en otra sombra y en otra


y andar con suavidad y con desenvoltura 

de fumador viajero


para que a cada paso un territorio

o una conmoción o una contrariedad


nos reconcilien con la vida pequeña 

y su muerte pequeña


para que un día 

nos queden 


unos cuantos recuerdos, decir estuve

estuve en tal pasión, en tal retazo de sol 


estuve, por ejemplo

en la feria de tilcara una mañana


con un pedazo de asado, una amistad tranquila

la mesa clara, las lagañas del perro, una conversación


y afuera, las tortilleras de la puna 

chapoteando con los bombines en la nieve


para que bebamos la dulce fritura 

del vendedor de punta lara


es necesario no asustarse de partir y volver

camaradas, de perderse en un bondi


y quedarse varadas

en una fundición de cielo

y montaña y playa y yunga y tierra


parda que anuncien los caminos

que se van y que vuelven


bajo el fin del armisticio al son

de esta vez quizá a nuestro favor


por un momento al menos grácil

grácil y breve


y nos olvidemos compañeras

no sólo de las olas


tiernas como eso, como olas

que acuerpamos calientes, somos


paladar de estas áureas

comillas de la noche


superpuestas en colpas tequeñas

bordemares, grasientas


muchedumbres y canciones, canciones

para que bebamos

la obscena fritura del vendedor de punta lara
